routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomepageController@index')->name('homepage');

Auth::routes(['register' => false]);

Route::prefix('admin')->middleware('auth', 'is_admin')->name('admin.')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('type_card', 'TypeCardController');
    Route::resource('subtype_card', 'SubtypeCardController');
    Route::resource('set', 'SetController');
    Route::resource('user', 'UserController');
    Route::resource('color', 'ColorController');
    Route::resource('rarity', 'RarityController');
    Route::resource('card', 'CardController');
});

app/Set.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Set extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/SetController.php
<?php

namespace App\Http\Controllers;

use App\Set;
use Illuminate\Http\Request;

class SetController extends Controller
{
    public function index()
    {
        $sets = Set::all();

        return view('admin.set.index', [
            'sets' => $sets,
        ]);
    }

    public function create()
    {
        return view('admin.set.create');
    }

    public function store(Request $request)
    {
        Set::create($request->all());
        return redirect(route('admin.set.index'));
    }

    public function show(Set $set)
    {
        return redirect(route('admin.set.index'));
    }

    public function edit(Set $set)
    {
        $set = Set::find($set->id);
        return view('admin.set.edit', [
            'set' => $set,
        ]);
    }

    public function update(Request $request, Set $set)
    {
        $set = Set::find($set->id);
        $set->fill($request->all());
        $set->save();
        return redirect(route('admin.set.index'));
    }

    public function destroy(Set $set)
    {
        Set::find($set->id)->delete();
        return redirect(route('admin.set.index'));
    }
}

resources/views/admin/set/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.set.store') }}" method="post">
        <div class="form-group">
            {{ csrf_field() }}
            <label>
                Название<br>
                <input type="text" name="name"><br>
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/set/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.set.update', $set->id) }}" method="post">
        <div class="form-group">
            {{ method_field('put') }}
            {{ csrf_field() }}
            <label>
                Название<br>
                <input type="text" name="name" value="{{ $set->name }}"><br>
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/set/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="btn-group">
        <a class="btn btn-primary mb-3" href="{{ route('admin.set.create') }}"><i class="fa fa-plus"></i> Добавить</a>
    </div>
    <div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($sets as $set)
                <tr>
                    <th scope="col">{{ $set->id }}</th>
                    <td>{{ $set->name }}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-block" href="{{ route('admin.set.edit', $set->id) }}"><i class="fa fa-edit"></i></a>
                            <form action="{{ route('admin.set.destroy', $set->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection