routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomepageController@index')->name('homepage');

Auth::routes(['register' => false]);

Route::prefix('admin')->middleware('auth', 'is_admin')->name('admin.')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('type_card', 'TypeCardController');
    Route::resource('subtype_card', 'SubtypeCardController');
    Route::resource('set', 'SetController');
    Route::resource('user', 'UserController');
    Route::resource('color', 'ColorController');
    Route::resource('rarity', 'RarityController');
    Route::resource('card', 'CardController');
});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function index()
    {
        $users = User::all();

        return view('admin.user.index', [
            'users' => $users,
        ]);
    }

    public function create()
    {
        return view('admin.user.create');
    }

    public function store(Request $request)
    {
        $request->merge(['password' => Hash::make($request->password)]);
        if ($request->is_admin == 'on') {
            $request->merge(['is_admin' => 1]);
        } else {
            $request->merge(['is_admin' => 0]);
        }
        User::create($request->all());
        return redirect(route('admin.user.index'));
    }

    public function show(User $user)
    {
        return redirect(route('admin.user.index'));
    }

    public function edit(User $user)
    {
        $user = User::find($user->id);
        return view('admin.user.edit', [
            'user' => $user,
        ]);
    }

    public function update(Request $request, User $user)
    {
        $request->merge(['password' => Hash::make($request->password)]);
        if ($request->is_admin == 'on') {
            $request->merge(['is_admin' => 1]);
        } else {
            $request->merge(['is_admin' => 0]);
        }
        $user = User::find($user->id);
        $user->fill($request->all());
        $user->save();
        return redirect(route('admin.user.index'));
    }

    public function destroy(User $user)
    {
        User::find($user->id)->delete();
        return redirect(route('admin.user.index'));
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.user.store') }}" method="post">
        <div class="form-group">
            {{ csrf_field() }}
            <label>
                Имя<br>
                <input type="text" name="name"><br>
            </label><br>
            <label>
                Email<br>
                <input type="email" name="email"><br>
            </label><br>
            <label>
                Пароль<br>
                <input type="password" name="password" required><br>
            </label><br>
            <label>
                <input type="checkbox" name="is_admin"> Администратор
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.user.update', $user->id) }}" method="post">
        <div class="form-group">
            {{ method_field('put') }}
            {{ csrf_field() }}
            <label>
                Имя<br>
                <input type="text" name="name" value="{{ $user->name }}"><br>
            </label><br>
            <label>
                Email<br>
                <input type="email" name="email" value="{{ $user->email }}"><br>
            </label><br>
            <label>
                Пароль<br>
                <input type="password" name="password" required><br>
            </label><br>
            <label>
                <input type="checkbox" name="is_admin"> Администратор
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/user/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="btn-group">
        <a class="btn btn-primary mb-3" href="{{ route('admin.user.create') }}"><i class="fa fa-plus"></i> Добавить</a>
    </div>
    <div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Администратор</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <th scope="col">{{ $user->id }}</th>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                        @if($user->is_admin)
                            <i class="fa fa-check text-success"></i>
                        @else
                            <i class="fa fa-times text-danger"></i>
                        @endif
                    </td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-block" href="{{ route('admin.user.edit', $user->id) }}"><i class="fa fa-edit"></i></a>
                            <form action="{{ route('admin.user.destroy', $user->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection