routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomepageController@index')->name('homepage');

Auth::routes(['register' => false]);

Route::prefix('admin')->middleware('auth', 'is_admin')->name('admin.')->group(function () {
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::resource('type_card', 'TypeCardController');
    Route::resource('subtype_card', 'SubtypeCardController');
    Route::resource('set', 'SetController');
    Route::resource('user', 'UserController');
    Route::resource('color', 'ColorController');
    Route::resource('rarity', 'RarityController');
    Route::resource('card', 'CardController');
});

app/Color.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Color extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/ColorController.php
<?php

namespace App\Http\Controllers;

use App\Color;
use Illuminate\Http\Request;

class ColorController extends Controller
{
    public function index()
    {
        $colors = Color::all();

        return view('admin.color.index', [
            'colors' => $colors,
        ]);
    }

    public function create()
    {
        return view('admin.color.create');
    }

    public function store(Request $request)
    {
        Color::create($request->all());
        return redirect(route('admin.color.index'));
    }

    public function show(Color $color)
    {
        return redirect(route('admin.color.index'));
    }

    public function edit(Color $color)
    {
        $color = Color::find($color->id);
        return view('admin.color.edit', [
            'color' => $color
        ]);
    }

    public function update(Request $request, Color $color)
    {
        $color = Color::find($color->id);
        $color->fill($request->all());
        $color->save();
        return redirect(route('admin.color.index'));
    }

    public function destroy(Color $color)
    {
        Color::find($color->id)->delete();
        return redirect(route('admin.color.index'));
    }
}

resources/views/admin/color/create.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.color.store') }}" method="post">
        <div class="form-group">
            {{ csrf_field() }}
            <label>
                Название<br>
                <input type="text" name="name"><br>
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/color/edit.blade.php
@extends('admin.layouts.app')

@section('content')
    <form action="{{ route('admin.color.update', $color->id) }}" method="post">
        <div class="form-group">
            {{ method_field('put') }}
            {{ csrf_field() }}
            <label>
                Название<br>
                <input type="text" name="name" value="{{ $color->name }}"><br>
            </label><br>
            <button class="btn btn-primary"><i class="fa fa-save"></i> Сохранить</button>
        </div>
    </form>
@endsection

resources/views/admin/color/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <div class="btn-group">
        <a class="btn btn-primary mb-3" href="{{ route('admin.color.create') }}"><i class="fa fa-plus"></i> Добавить</a>
    </div>
    <div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            @foreach($colors as $color)
                <tr>
                    <th scope="col">{{ $color->id }}</th>
                    <td>{{ $color->name }}</td>
                    <td>
                        <div class="btn-group">
                            <a class="btn btn-block" href="{{ route('admin.color.edit', $color->id) }}"><i class="fa fa-edit"></i></a>
                            <form action="{{ route('admin.color.destroy', $color->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <button class="btn btn-danger" type="submit"><i class="fa fa-trash"></i></button>
                            </form>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection